:bricks: ci: Generate Dockerfile and first continuos integration

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -7,7 +7,7 @@ jobs:
   build:
     name: Build and Push to Docker Hub
     runs-on: ubuntu-latest
-    needs: e2e-tests
+    needs: tests
 
     steps:
       - name: Checkout
@@ -36,8 +36,8 @@ jobs:
           push: true
           tags: lukasrib15dev/my-habbits:${{ steps.generate_tag.outputs.sha }},lukasrib15dev/my-habbits:latest
   
-  e2e-tests:
-      name: End-to-End Tests 
+  tests:
+      name: Run Tests 
       runs-on: ubuntu-latest
 
       services:
@@ -67,6 +67,15 @@ jobs:
   
         - name: Run Unit Tests
           run: pnpm run test
+
+        - name: Wait for PostgreSQL to be ready
+          run: |
+            for i in {1..10}; do
+              nc -z postgresDB 5432 && echo "Database is ready!" && exit 0
+              echo "Waiting for database..."
+              sleep 3
+            done
+            echo "Database failed to start" && exit 1
 
         - name: Generate Prisma Client
           env:
